services:
  cheer-next:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${PORT}:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"